// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhCr14-k25mm5EMFpffOqqUZniak3JGDQ',
    appId: '1:769202510609:web:c718cbcbd127ff96cc8ab0',
    messagingSenderId: '769202510609',
    projectId: 'donature-it-dive',
    authDomain: 'donature-it-dive.firebaseapp.com',
    databaseURL: 'https://donature-it-dive-default-rtdb.firebaseio.com',
    storageBucket: 'donature-it-dive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhrcxdU0LWwEhjPZ-6h_QYqBw9pPuaRT8',
    appId: '1:769202510609:android:bb1f27e18aa7856fcc8ab0',
    messagingSenderId: '769202510609',
    projectId: 'donature-it-dive',
    databaseURL: 'https://donature-it-dive-default-rtdb.firebaseio.com',
    storageBucket: 'donature-it-dive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhyF6BMauNwsgE28ldH4U8h7oEIzAHwnY',
    appId: '1:769202510609:ios:df78041fd6b532eacc8ab0',
    messagingSenderId: '769202510609',
    projectId: 'donature-it-dive',
    databaseURL: 'https://donature-it-dive-default-rtdb.firebaseio.com',
    storageBucket: 'donature-it-dive.appspot.com',
    iosClientId: '769202510609-lioqlshdvg43dc7ujvqbpb1b4f8flbla.apps.googleusercontent.com',
    iosBundleId: 'com.ItDive.donationNature',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhyF6BMauNwsgE28ldH4U8h7oEIzAHwnY',
    appId: '1:769202510609:ios:df78041fd6b532eacc8ab0',
    messagingSenderId: '769202510609',
    projectId: 'donature-it-dive',
    databaseURL: 'https://donature-it-dive-default-rtdb.firebaseio.com',
    storageBucket: 'donature-it-dive.appspot.com',
    iosClientId: '769202510609-lioqlshdvg43dc7ujvqbpb1b4f8flbla.apps.googleusercontent.com',
    iosBundleId: 'com.ItDive.donationNature',
  );
}
